#!/usr/bin/env python3
"""Generates lib/l10n/app_en.arb and app_ar.arb from the table below.

You can edit the .arb files directly instead - this script only exists to keep
the English and Arabic strings side by side while the template is developed.
Run:  python3 tools/gen_arb.py && flutter gen-l10n
"""
import json, re

def plural(count, zero=None, one=None, two=None, few=None, many=None, other=None):
    parts = []
    if zero is not None: parts.append(f"=0{{{zero}}}")
    if one is not None: parts.append(f"=1{{{one}}}")
    if two is not None: parts.append(f"=2{{{two}}}")
    if few is not None: parts.append(f"few{{{few}}}")
    if many is not None: parts.append(f"many{{{many}}}")
    parts.append(f"other{{{other}}}")
    return "{%s, plural, %s}" % (count, " ".join(parts))

# key: (english, arabic, {placeholder: type})
S = {
 # generic
 "appName": ("Darklet", "Darklet", {}),
 "skip": ("Skip", "تخطي", {}),
 "next": ("Next", "التالي", {}),
 "getStarted": ("Get started", "ابدأ الآن", {}),
 "cancel": ("Cancel", "إلغاء", {}),
 "delete": ("Delete", "حذف", {}),
 "edit": ("Edit", "تعديل", {}),
 "remove": ("Remove", "إزالة", {}),
 "undo": ("Undo", "تراجع", {}),
 "retry": ("Retry", "إعادة المحاولة", {}),
 "tryAgain": ("Try again", "حاول مرة أخرى", {}),
 "reset": ("Reset", "إعادة ضبط", {}),
 "all": ("All", "الكل", {}),
 "or": ("or", "أو", {}),
 "free": ("Free", "مجاني", {}),
 "change": ("Change", "تغيير", {}),
 "viewAll": ("View all", "عرض الكل", {}),
 "viewCart": ("View cart", "عرض السلة", {}),
 "somethingWentWrong": ("Something went wrong", "حدث خطأ ما", {}),
 "tryAgainMessage": ("Please check your connection and try again.", "يرجى التحقق من الاتصال والمحاولة مرة أخرى.", {}),
 "noResults": ("No results found", "لا توجد نتائج", {}),
 "fieldRequired": ("This field is required", "هذا الحقل مطلوب", {}),
 "invalidEmail": ("Enter a valid email address", "أدخل بريدًا إلكترونيًا صالحًا", {}),
 "passwordTooShort": ("Password must be at least {n} characters", "يجب ألا تقل كلمة المرور عن {n} أحرف", {"n": "int"}),
 "passwordsDontMatch": ("Passwords don't match", "كلمتا المرور غير متطابقتين", {}),
 # onboarding
 "onboardTitle1": ("Start by creating\nan account", "ابدأ بإنشاء\nحساب", {}),
 "onboardBody1": ("Discover a smarter way to shop.\nSign in to get started.", "اكتشف طريقة أذكى للتسوق.\nسجّل الدخول للبدء.", {}),
 "onboardTitle2": ("Find what you\nare looking for", "اعثر على ما\nتبحث عنه", {}),
 "onboardBody2": ("Browse phones, consoles, laptops and audio.\nFilter and sort in seconds.", "تصفح الهواتف وأجهزة الألعاب والحواسيب والصوتيات.\nصفّ وافرز في ثوانٍ.", {}),
 "onboardTitle3": ("You're all set!", "كل شيء جاهز!", {}),
 "onboardBody3": ("Your order is placed and on its way.\nSit back, relax - we'll handle the rest.", "تم تقديم طلبك وهو في الطريق.\nاسترح، ونحن نتولى الباقي.", {}),
 # auth
 "welcomeBack": ("Welcome back", "مرحبًا بعودتك", {}),
 "enterDetails": ("Enter your details below", "أدخل بياناتك أدناه", {}),
 "email": ("Email address", "البريد الإلكتروني", {}),
 "emailHint": ("you@example.com", "you@example.com", {}),
 "password": ("Password", "كلمة المرور", {}),
 "confirmPassword": ("Confirm password", "تأكيد كلمة المرور", {}),
 "forgotPassword": ("Forgot your password?", "هل نسيت كلمة المرور؟", {}),
 "signIn": ("Sign in", "تسجيل الدخول", {}),
 "signUp": ("Sign up", "إنشاء حساب", {}),
 "continueWithGoogle": ("Continue with Google", "المتابعة عبر Google", {}),
 "noAccount": ("Don't have an account?", "ليس لديك حساب؟", {}),
 "haveAccount": ("Already have an account?", "لديك حساب بالفعل؟", {}),
 "createAccount": ("Create account", "إنشاء حساب", {}),
 "registerSubtitle": ("Join Darklet in a few seconds", "انضم إلى Darklet في ثوانٍ", {}),
 "fullName": ("Full name", "الاسم الكامل", {}),
 "forgotPasswordTitle": ("Reset password", "إعادة تعيين كلمة المرور", {}),
 "forgotPasswordSubtitle": ("We'll email you a link to reset your password", "سنرسل إليك رابطًا لإعادة تعيين كلمة المرور", {}),
 "sendResetLink": ("Send reset link", "إرسال رابط الاستعادة", {}),
 "resetLinkSent": ("If the account exists, a reset link is on its way.", "إذا كان الحساب موجودًا فسيصلك رابط الاستعادة قريبًا.", {}),
 "demoHint": ("Demo account: {email} / {password}\nTap to fill", "حساب تجريبي: {email} / {password}\nاضغط للتعبئة", {"email": "String", "password": "String"}),
 "errInvalidCredentials": ("Incorrect email or password", "البريد الإلكتروني أو كلمة المرور غير صحيحة", {}),
 "errEmailInUse": ("An account with this email already exists", "يوجد حساب بهذا البريد الإلكتروني بالفعل", {}),
 "errWeakPassword": ("That password is too weak", "كلمة المرور ضعيفة جدًا", {}),
 "errUserNotFound": ("No account found", "لم يتم العثور على حساب", {}),
 "errRequiresRecentLogin": ("Please sign in again to continue", "يرجى تسجيل الدخول مرة أخرى للمتابعة", {}),
 "errCancelled": ("Sign-in was cancelled", "تم إلغاء تسجيل الدخول", {}),
 "errNetwork": ("Network error. Check your connection.", "خطأ في الشبكة. تحقق من اتصالك.", {}),
 # nav / home
 "navHome": ("Home", "الرئيسية", {}),
 "navCategories": ("Categories", "الفئات", {}),
 "navWishlist": ("Wishlist", "المفضلة", {}),
 "navProfile": ("Profile", "حسابي", {}),
 "hello": ("Hello, {name}", "مرحبًا، {name}", {"name": "String"}),
 "welcomeTo": ("Welcome to", "مرحبًا بك في", {}),
 "searchProducts": ("Search products...", "ابحث عن المنتجات...", {}),
 "promoTitle": ("Up to 30% off", "خصم يصل إلى 30%", {}),
 "promoSubtitle": ("Flash sale on phones, laptops and audio", "تخفيضات على الهواتف والحواسيب والصوتيات", {}),
 "categories": ("Categories", "الفئات", {}),
 "flashSales": ("Flash sales", "عروض سريعة", {}),
 "recentlyViewed": ("Recently viewed", "شوهدت مؤخرًا", {}),
 "categoryTitleA": ("Cate", "", {}),
 "categoryTitleB": ("gory", "الفئات", {}),
 "catPhones": ("Phones", "الهواتف", {}),
 "catConsoles": ("Consoles", "أجهزة الألعاب", {}),
 "catLaptops": ("Laptops", "الحواسيب", {}),
 "catAudio": ("Audio", "الصوتيات", {}),
 "catWearables": ("Wearables", "الأجهزة القابلة للارتداء", {}),
 "categorySection": ("{name} section", "قسم {name}", {"name": "String"}),
 "sectionTitle": ("{name} section", "قسم {name}", {"name": "String"}),
 "wishlistTitleA": ("Wish", "", {}),
 "wishlistTitleB": ("list", "المفضلة", {}),
 "searchWishlist": ("Search your wishlist", "ابحث في المفضلة", {}),
 "wishlistEmptyTitle": ("Your wishlist is empty", "قائمة المفضلة فارغة", {}),
 "wishlistEmptyMessage": ("Tap the heart on any product to save it here.", "اضغط على القلب في أي منتج لحفظه هنا.", {}),
 "startShopping": ("Start shopping", "ابدأ التسوق", {}),
 "addToWishlist": ("Add to wishlist", "أضف إلى المفضلة", {}),
 "removeFromWishlist": ("Remove from wishlist", "أزل من المفضلة", {}),
 # products
 "filters": ("Filters", "التصفية", {}),
 "category": ("Category", "الفئة", {}),
 "brand": ("Brand", "العلامة التجارية", {}),
 "priceRange": ("Price range", "نطاق السعر", {}),
 "sortBy": ("Sort by", "ترتيب حسب", {}),
 "sortRelevance": ("Relevance", "الأكثر صلة", {}),
 "sortPriceLow": ("Price: low to high", "السعر: من الأقل للأعلى", {}),
 "sortPriceHigh": ("Price: high to low", "السعر: من الأعلى للأقل", {}),
 "sortTopRated": ("Top rated", "الأعلى تقييمًا", {}),
 "applyFilters": ("Apply filters", "تطبيق التصفية", {}),
 "noProductsTitle": ("No products found", "لا توجد منتجات", {}),
 "noProductsMessage": ("Try changing your search or filters.", "جرّب تغيير البحث أو التصفية.", {}),
 "resultsCount": ("{count} results{more}", "{count} نتيجة{more}", {"count": "int", "more": "String"}),
 "details": ("Details", "التفاصيل", {}),
 "description": ("Description", "الوصف", {}),
 "specifications": ("Specifications", "المواصفات", {}),
 "inStock": ("In stock", "متوفر", {}),
 "outOfStock": ("Out of stock", "غير متوفر", {}),
 "onlyLeft": ("Only {count} left", "متبقي {count} فقط", {"count": "int"}),
 "addToCart": ("Add to cart", "أضف إلى السلة", {}),
 "addedToCart": ("Added to cart", "تمت الإضافة إلى السلة", {}),
 "reviewsCount": (plural("count", zero="No reviews", one="1 review", other="{count} reviews"),
                  plural("count", zero="لا مراجعات", one="مراجعة واحدة", two="مراجعتان", few="{count} مراجعات", many="{count} مراجعة", other="{count} مراجعة"), {"count": "int"}),
 "seeReviews": ("See all reviews ({count})", "عرض كل المراجعات ({count})", {"count": "int"}),
 # reviews
 "reviews": ("Reviews", "المراجعات", {}),
 "writeReview": ("Write a review", "اكتب مراجعة", {}),
 "noReviewsTitle": ("No reviews yet", "لا توجد مراجعات بعد", {}),
 "noReviewsMessage": ("Be the first to share your thoughts.", "كن أول من يشارك رأيه.", {}),
 "yourRating": ("Your rating", "تقييمك", {}),
 "yourReview": ("Your review", "مراجعتك", {}),
 "reviewHint": ("What did you like or dislike?", "ما الذي أعجبك أو لم يعجبك؟", {}),
 "ratingRequired": ("Please select a rating", "يرجى اختيار تقييم", {}),
 "submitReview": ("Submit review", "إرسال المراجعة", {}),
 "reviewThanks": ("Thanks for your review!", "شكرًا على مراجعتك!", {}),
 "starsCount": ("{n} stars", "{n} نجوم", {"n": "int"}),
 # cart
 "cartTitle": ("My cart", "سلتي", {}),
 "cartEmptyTitle": ("Your cart is empty", "سلتك فارغة", {}),
 "cartEmptyMessage": ("Looks like you haven't added anything yet.", "يبدو أنك لم تضف أي شيء بعد.", {}),
 "itemRemoved": ("Item removed", "تمت إزالة المنتج", {}),
 "itemsCount": (plural("count", one="1 item", other="{count} items"),
                plural("count", zero="لا عناصر", one="عنصر واحد", two="عنصران", few="{count} عناصر", many="{count} عنصرًا", other="{count} عنصر"), {"count": "int"}),
 "subtotal": ("Subtotal", "المجموع الفرعي", {}),
 "shippingAtCheckout": ("Shipping is calculated at checkout", "يتم احتساب الشحن عند إتمام الشراء", {}),
 "checkout": ("Checkout", "إتمام الشراء", {}),
 "items": ("Items", "المنتجات", {}),
 # checkout
 "deliveryAddress": ("Delivery address", "عنوان التوصيل", {}),
 "deliveryOption": ("Delivery option", "خيار التوصيل", {}),
 "deliveryStandard": ("Standard delivery", "توصيل عادي", {}),
 "deliveryExpress": ("Express delivery", "توصيل سريع", {}),
 "deliveryPickup": ("Store pickup", "الاستلام من المتجر", {}),
 "etaDays": ("{min}-{max} business days", "{min}-{max} أيام عمل", {"min": "int", "max": "int"}),
 "etaPickup": ("Ready within 24 hours", "جاهز خلال 24 ساعة", {}),
 "paymentMethod": ("Payment method", "طريقة الدفع", {}),
 "payCard": ("Credit / debit card", "بطاقة ائتمان / خصم", {}),
 "payCardSubtitle": ("Visa, Mastercard and more", "فيزا وماستركارد وغيرها", {}),
 "payCardSecure": ("Pay securely with Stripe", "ادفع بأمان عبر Stripe", {}),
 "payCod": ("Cash on delivery", "الدفع عند الاستلام", {}),
 "payCodSubtitle": ("Pay when your order arrives", "ادفع عند وصول طلبك", {}),
 "addCard": ("Add card", "إضافة بطاقة", {}),
 "addNewCard": ("Add new card", "إضافة بطاقة جديدة", {}),
 "saveCard": ("Save card", "حفظ البطاقة", {}),
 "changeCard": ("Use another card", "استخدام بطاقة أخرى", {}),
 "cvcConfirm": ("Security code (CVC)", "رمز الأمان (CVC)", {}),
 "noCardsTitle": ("No saved cards", "لا توجد بطاقات محفوظة", {}),
 "noCardsMessage": ("Add a card to pay with. You can add more cards any time.", "أضف بطاقة للدفع بها. يمكنك إضافة بطاقات أخرى في أي وقت.", {}),
 "addCardFirst": ("Please add a card to continue", "يرجى إضافة بطاقة للمتابعة", {}),
 "expiresOn": ("Expires {date}", "تنتهي في {date}", {"date": "String"}),
 "cardSaveNote": ("We only keep the last 4 digits. Your CVC is never stored.", "نحتفظ بآخر 4 أرقام فقط. لا يتم حفظ رمز CVC أبدًا.", {}),
 # guest
 "guest": ("Guest", "زائر", {}),
 "continueAsGuest": ("Continue as guest", "المتابعة كزائر", {}),
 "signInRequiredTitle": ("Sign in to continue", "سجّل الدخول للمتابعة", {}),
 "signInRequiredMessage": ("Create a free account or sign in to checkout, review products and track orders. Your cart is kept.", "أنشئ حسابًا مجانيًا أو سجّل الدخول لإتمام الشراء وتقييم المنتجات وتتبع الطلبات. سلتك محفوظة.", {}),
 "guestProfileMessage": ("Sign in to manage orders, addresses and cards", "سجّل الدخول لإدارة الطلبات والعناوين والبطاقات", {}),
 "notNow": ("Not now", "ليس الآن", {}),
 # orders
 "cancelOrder": ("Cancel order", "إلغاء الطلب", {}),
 "keepOrder": ("Keep order", "الاحتفاظ بالطلب", {}),
 "cancelOrderConfirm": ("Are you sure you want to cancel this order? This can't be undone.", "هل أنت متأكد من إلغاء هذا الطلب؟ لا يمكن التراجع عن ذلك.", {}),
 "orderCancelled": ("Order cancelled", "تم إلغاء الطلب", {}),
 "cancelFailed": ("This order can't be cancelled any more", "لا يمكن إلغاء هذا الطلب بعد الآن", {}),
 "buyAgain": ("Buy again", "اشترِ مرة أخرى", {}),
 "itemsAddedToCart": (plural("count", one="1 item added to your cart", other="{count} items added to your cart"), plural("count", one="تمت إضافة عنصر واحد إلى سلتك", two="تمت إضافة عنصرين إلى سلتك", few="تمت إضافة {count} عناصر إلى سلتك", many="تمت إضافة {count} عنصرًا إلى سلتك", other="تمت إضافة {count} عنصر إلى سلتك"), {"count": "int"}),
 # cards
 "paymentMethods": ("Payment methods", "طرق الدفع", {}),
 "deleteCard": ("Delete card", "حذف البطاقة", {}),
 "deleteCardConfirm": ("Remove the card ending in {last4}?", "هل تريد إزالة البطاقة التي تنتهي بـ {last4}؟", {"last4": "String"}),
 "cardsEmptyMessage": ("Add a card to pay faster at checkout.", "أضف بطاقة لتدفع بشكل أسرع عند إتمام الشراء.", {}),
 # coupons
 "promoCode": ("Promo code", "رمز الخصم", {}),
 "enterPromoCode": ("Enter promo code", "أدخل رمز الخصم", {}),
 "apply": ("Apply", "تطبيق", {}),
 "discount": ("Discount", "الخصم", {}),
 "couponApplied": ("{code} applied", "تم تطبيق {code}", {"code": "String"}),
 "couponNotFound": ("This code isn't valid", "هذا الرمز غير صالح", {}),
 "couponMinSubtotal": ("Spend at least {amount} to use this code", "أنفق {amount} على الأقل لاستخدام هذا الرمز", {"amount": "String"}),
 # search / offline
 "recentSearches": ("Recent searches", "عمليات البحث الأخيرة", {}),
 "clearAll": ("Clear all", "مسح الكل", {}),
 "popularSearches": ("Popular searches", "عمليات بحث شائعة", {}),
 "offlineBanner": ("No internet connection", "لا يوجد اتصال بالإنترنت", {}),
 "backOnline": ("Back online", "عاد الاتصال", {}),
 "orderSummary": ("Order summary", "ملخص الطلب", {}),
 "delivery": ("Delivery", "التوصيل", {}),
 "total": ("Total", "الإجمالي", {}),
 "placeOrder": ("Place order", "تأكيد الطلب", {}),
 "continueToPayment": ("Continue to payment", "المتابعة للدفع", {}),
 "selectAddressFirst": ("Please add a delivery address first", "يرجى إضافة عنوان توصيل أولًا", {}),
 "payment": ("Payment", "الدفع", {}),
 "cardNumber": ("Card number", "رقم البطاقة", {}),
 "cardHolder": ("Name on card", "الاسم على البطاقة", {}),
 "expiry": ("Expiry date", "تاريخ الانتهاء", {}),
 "invalidCardNumber": ("Enter a valid card number", "أدخل رقم بطاقة صالحًا", {}),
 "invalidExpiry": ("Enter a valid expiry (MM/YY)", "أدخل تاريخ انتهاء صالحًا (شهر/سنة)", {}),
 "invalidCvc": ("Invalid CVC", "رمز CVC غير صالح", {}),
 "payAmount": ("Pay {amount}", "ادفع {amount}", {"amount": "String"}),
 "processingPayment": ("Processing your payment...", "جارٍ معالجة الدفع...", {}),
 "paymentFailedTitle": ("Payment failed", "فشلت عملية الدفع", {}),
 "paymentDeclined": ("Your card was declined. Please try another card.", "تم رفض بطاقتك. يرجى تجربة بطاقة أخرى.", {}),
 "paymentFailedGeneric": ("We couldn't process your payment. You were not charged.", "تعذرت معالجة الدفع. لم يتم خصم أي مبلغ.", {}),
 "changePaymentMethod": ("Change payment method", "تغيير طريقة الدفع", {}),
 "testCardHint": ("Test mode: use 4242 4242 4242 4242. Card 4000 0000 0000 0002 is declined.", "وضع الاختبار: استخدم 4242 4242 4242 4242. البطاقة 4000 0000 0000 0002 يتم رفضها.", {}),
 "stripeSheetHint": ("You'll enter your card details in a secure Stripe sheet.", "ستُدخل بيانات بطاقتك في نافذة Stripe الآمنة.", {}),
 "orderPlacedTitle": ("Order placed!", "تم تأكيد الطلب!", {}),
 "orderPlacedMessage": ("Thank you for your purchase. We'll notify you as your order progresses.", "شكرًا على طلبك. سنخبرك عند كل تحديث لحالة الطلب.", {}),
 "orderNumber": ("Order {id}", "الطلب {id}", {"id": "String"}),
 "trackOrder": ("Track order", "تتبع الطلب", {}),
 "continueShopping": ("Continue shopping", "متابعة التسوق", {}),
 "notifOrderPlacedTitle": ("Order placed", "تم تأكيد الطلب", {}),
 "notifOrderPlacedBody": ("Your order {id} was placed successfully.", "تم تأكيد طلبك {id} بنجاح.", {"id": "String"}),
 # orders
 "myOrders": ("My orders", "طلباتي", {}),
 "ordersEmptyTitle": ("No orders yet", "لا توجد طلبات بعد", {}),
 "ordersEmptyMessage": ("When you place an order it will show up here.", "ستظهر طلباتك هنا بعد تقديمها.", {}),
 "orderNotFound": ("Order not found", "الطلب غير موجود", {}),
 "orderTracking": ("Order tracking", "تتبع الطلب", {}),
 "orderCancelledMessage": ("This order was cancelled.", "تم إلغاء هذا الطلب.", {}),
 "statusPlaced": ("Order placed", "تم تقديم الطلب", {}),
 "statusConfirmed": ("Confirmed", "تم التأكيد", {}),
 "statusShipped": ("Shipped", "تم الشحن", {}),
 "statusOutForDelivery": ("Out for delivery", "في الطريق إليك", {}),
 "statusDelivered": ("Delivered", "تم التسليم", {}),
 "statusCancelled": ("Cancelled", "ملغي", {}),
 # addresses
 "myAddresses": ("My addresses", "عناويني", {}),
 "selectAddress": ("Select address", "اختر العنوان", {}),
 "addAddress": ("Add address", "إضافة عنوان", {}),
 "editAddress": ("Edit address", "تعديل العنوان", {}),
 "saveAddress": ("Save address", "حفظ العنوان", {}),
 "deleteAddress": ("Delete address", "حذف العنوان", {}),
 "deleteAddressConfirm": ("This address will be removed from your address book.", "سيتم حذف هذا العنوان من دفتر العناوين.", {}),
 "addressesEmptyTitle": ("No saved addresses", "لا توجد عناوين محفوظة", {}),
 "addressesEmptyMessage": ("Add an address to speed up checkout.", "أضف عنوانًا لتسريع إتمام الشراء.", {}),
 "addressLabel": ("Label", "التسمية", {}),
 "addressLabelHint": ("Home, Work...", "المنزل، العمل...", {}),
 "phone": ("Phone number", "رقم الهاتف", {}),
 "streetAddress": ("Street address", "عنوان الشارع", {}),
 "city": ("City", "المدينة", {}),
 "stateRegion": ("State / Region", "الولاية / المنطقة", {}),
 "zipCode": ("ZIP / Postal code", "الرمز البريدي", {}),
 "country": ("Country", "الدولة", {}),
 "setAsDefault": ("Set as default", "تعيين كافتراضي", {}),
 "defaultLabel": ("Default", "افتراضي", {}),
 "addressPrivacy": ("Your address is only used to deliver your orders.", "يُستخدم عنوانك فقط لتوصيل طلباتك.", {}),
 # profile / settings
 "account": ("Account", "الحساب", {}),
 "editProfile": ("Edit profile", "تعديل الملف الشخصي", {}),
 "saveChanges": ("Save changes", "حفظ التغييرات", {}),
 "profileUpdated": ("Profile updated", "تم تحديث الملف الشخصي", {}),
 "changePassword": ("Change password", "تغيير كلمة المرور", {}),
 "currentPassword": ("Current password", "كلمة المرور الحالية", {}),
 "newPassword": ("New password", "كلمة المرور الجديدة", {}),
 "updatePassword": ("Update password", "تحديث كلمة المرور", {}),
 "passwordChanged": ("Password changed", "تم تغيير كلمة المرور", {}),
 "notifications": ("Notifications", "الإشعارات", {}),
 "markAllRead": ("Mark all read", "تعليم الكل كمقروء", {}),
 "notificationsEmptyTitle": ("No notifications", "لا توجد إشعارات", {}),
 "notificationsEmptyMessage": ("Order updates and offers will appear here.", "ستظهر هنا تحديثات الطلبات والعروض.", {}),
 "darkMode": ("Dark mode", "الوضع الداكن", {}),
 "settings": ("Settings", "الإعدادات", {}),
 "appearance": ("Appearance", "المظهر", {}),
 "themeSystem": ("System default", "حسب النظام", {}),
 "themeLight": ("Light", "فاتح", {}),
 "themeDark": ("Dark", "داكن", {}),
 "language": ("Language", "اللغة", {}),
 "about": ("About", "حول", {}),
 "version": ("Version", "الإصدار", {}),
 "demoMode": ("Demo mode", "الوضع التجريبي", {}),
 "liveMode": ("Live mode", "الوضع المباشر", {}),
 "logOut": ("Log out", "تسجيل الخروج", {}),
 "logOutConfirm": ("Are you sure you want to log out?", "هل أنت متأكد من تسجيل الخروج؟", {}),
}

TYPES = {"int": "int", "String": "String"}

def build(idx):
    out = {"@@locale": ["en", "ar"][idx]}
    for k, (en, ar, ph) in S.items():
        out[k] = (en, ar)[idx]
        if ph:
            out["@" + k] = {"placeholders": {p: {"type": t} for p, t in ph.items()}}
    return out

for idx, code in enumerate(["en", "ar"]):
    # sanity: every placeholder used must be declared
    for k, (en, ar, ph) in S.items():
        used = set(re.findall(r"\{([A-Za-z_]\w*)(?:,|\})", (en, ar)[idx], re.ASCII))
        used -= {"plural"}
        assert used <= set(ph), (k, used, ph)
    with open(f"lib/l10n/app_{code}.arb", "w", encoding="utf-8") as f:
        json.dump(build(idx), f, ensure_ascii=False, indent=2)
        f.write("\n")
print(len(S), "strings")
